version: '3'

services:   
  app_watcher:
    build: ./
    image: test-gazin
    restart: always
    ports:
      - ${PORT}:${PORT}
    volumes: 
      - ./:/usr/www
    command: ["npm", "run", "dev"]

  app-db:
    image: postgres:alpine
    ports: 
      - '5432:5432'
    environment: 
      POSTGRES_PASSWORD: "Postgres2019!"
    volumes: 
      - ./volumes:/var/lib/postgresql/data